# .github/workflows/docker-publish-api-gateway.yml
name: Build and Push Docker Image (API Gateway)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-api-gateway: # Changed job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use the same secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Use the same secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Gateway Image
        uses: docker/build-push-action@v5
        with:
          # IMPORTANT: Set context to the api-gateway directory
          context: . # Adjust path if needed
          file: ./Dockerfile # Path to Dockerfile relative to repo root
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max